{
  "throws": "Await cannot be used as name inside an async function (2:7)"
}
